### PR TITLE
Passage view redesign

### PR DESCRIPTION
**Pull request by jankaszel**
### Functionality this PR provides:

* Add a passage JSON API endpoint (`/api/v1/passage/:urn`)
* Add a user JSON API endpoint (`/api/v1/user`)
* Add an interactive passage view _(powered by svelte)_ that supports full-window landscape views with vertical resizing
* Fixes a dependency security vulnerability

### How to test:

* Do a full rebuild of Brucheion (`rm Brucheion && make brucheion`) and simply navigate to the passage overview

### Please note:

* There is no option to have a portrait folio layout atm

### CODE REVIEW

**Comment by jankaszel** [comment]
@ThomasK81 that's the current state of the new passage view:

grafik

**Comment by ThomasK81** [comment]
I tested it and it looks great! Definitely like the clean look. The tool links are broken though (transcribe and multicompare). I can live with that for now, should we merge and patch later? Do you think, you could implement the portrait and the resizing before your holiday. If not, that's fine. The documentation is more important.

**Comment by jankaszel** [comment]
Oh I see! The passage URN is not passed down to the Go template, I'll fix that quickly. If there's some time left today I'll have a look at the resizing functionality. Portrait would bear too much work I guess...

**Comment by jankaszel** [comment]
@ThomasK81 vertical resizing works now and the tools links have been fixed! It's good to go I'd say, but you better have another look.

**Pull request merged**
